/**
 * Patch no SDK MCP ESM: intercepta a conversão Zod -> JSON Schema
 * e remove todos os $ref inlineando os schemas.
 *
 * Estratégia: modifica o arquivo zod-json-schema-compat.js do SDK no disco,
 * injetando sanitizeInputSchema como import local. Idempotente.
 *
 * O patch DEVE ser importado ANTES de qualquer import do @modelcontextprotocol/sdk
 * para que o Node.js ESM carregue o arquivo modificado na primeira vez.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const sdkDir = path.resolve(
  __dirname,
  "../node_modules/@modelcontextprotocol/sdk/dist/esm/server"
);

const compatPath = path.join(sdkDir, "zod-json-schema-compat.js");
const sanitizePath = path.join(sdkDir, "sanitize-schema.js");

const SANITIZE_MARKER = "/* SANITIZE_PATCH_APPLIED */";

const SANITIZE_CODE = `
// Auto-generated by schema-patch.ts — do not edit manually
export function resolveRefs(schema, root, depth = 0, maxDepth = 50) {
  if (depth > maxDepth) {
    console.warn(\`[resolveRefs] Max depth \${maxDepth} atingido\`);
    return schema;
  }
  if (root === undefined) root = schema;
  if (schema === null || typeof schema !== "object") return schema;
  if (Array.isArray(schema)) return schema.map((item) => resolveRefs(item, root, depth + 1, maxDepth));

  if ("$ref" in schema) {
    const refPath = schema["$ref"];
    const resolved = resolveRefPath(root, refPath);
    if (resolved !== null) {
      const inlined = JSON.parse(JSON.stringify(resolved));
      if (typeof inlined === "object" && inlined !== null && "$ref" in inlined) {
        delete inlined["$ref"];
      }
      const { $ref, ...rest } = schema;
      const merged = { ...inlined, ...rest };
      return resolveRefs(merged, root, depth + 1, maxDepth);
    }
    console.warn(\`[resolveRefs] Não conseguiu resolver: \${refPath}\`);
  }

  const result = {};
  for (const [key, value] of Object.entries(schema)) {
    result[key] = resolveRefs(value, root, depth + 1, maxDepth);
  }
  return result;
}

function resolveRefPath(root, refPath) {
  if (!refPath.startsWith("#/")) return null;
  const parts = refPath.slice(2).split("/");
  let current = root;
  for (const part of parts) {
    if (current !== null && typeof current === "object" && part in current) {
      current = current[part];
    } else {
      return null;
    }
  }
  return current;
}

export function sanitizeInputSchema(schema) {
  const resolved = resolveRefs(schema);
  const str = JSON.stringify(resolved);
  if (str.includes('"$ref"')) {
    console.warn("[sanitizeInputSchema] AVISO: Schema ainda contém $ref após resolução!");
    console.warn("[sanitizeInputSchema] Schema:", JSON.stringify(resolved, null, 2).slice(0, 500));
  }
  return resolved;
}
`;

const NEW_FUNC_BODY = `export function toJsonSchemaCompat(schema, opts) {
    let result;
    if (isZ4Schema(schema)) {
        result = z4mini.toJSONSchema(schema, {
            target: mapMiniTarget(opts?.target),
            io: opts?.pipeStrategy ?? 'input'
        });
    } else {
        result = zodToJsonSchema(schema, {
            strictUnions: opts?.strictUnions ?? true,
            pipeStrategy: opts?.pipeStrategy ?? 'input'
        });
    }
    if (opts?.pipeStrategy === "output") {
        return result;
    }
    return sanitizeInputSchema(result);
}`;

function ensureSanitizeModule(): void {
  if (!fs.existsSync(sdkDir)) {
    fs.mkdirSync(sdkDir, { recursive: true });
  }
  if (!fs.existsSync(sanitizePath) || !fs.readFileSync(sanitizePath, "utf-8").includes("resolveRefs")) {
    fs.writeFileSync(sanitizePath, SANITIZE_CODE, "utf-8");
  }
}

function replaceFunctionBody(content: string): string | null {
  const startMarker = "export function toJsonSchemaCompat(schema, opts) {";
  const startIdx = content.indexOf(startMarker);
  if (startIdx === -1) {
    return null;
  }

  let braceDepth = 0;
  let endIdx = -1;
  for (let i = startIdx + startMarker.length; i < content.length; i++) {
    if (content[i] === "{") {
      braceDepth++;
    } else if (content[i] === "}") {
      if (braceDepth === 0) {
        endIdx = i + 1;
        break;
      }
      braceDepth--;
    }
  }

  if (endIdx === -1) {
    return null;
  }

  return content.slice(0, startIdx) + NEW_FUNC_BODY + content.slice(endIdx);
}

function applyPatch(): boolean {
  if (!fs.existsSync(compatPath)) {
    console.error("[ue-mcp] AVISO: zod-json-schema-compat.js não encontrado em", compatPath);
    return false;
  }

  let original = fs.readFileSync(compatPath, "utf-8");
  if (original.includes(SANITIZE_MARKER)) {
    return true;
  }

  ensureSanitizeModule();

  // Adicionar import do sanitizeInputSchema após o último import
  const lines = original.split("\n");
  let lastImportIdx = -1;
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].trim().startsWith("import ")) {
      lastImportIdx = i;
    }
  }
  const importLine = `import { sanitizeInputSchema } from './sanitize-schema.js'; ${SANITIZE_MARKER}`;
  if (lastImportIdx >= 0) {
    lines.splice(lastImportIdx + 1, 0, importLine);
    original = lines.join("\n");
  } else {
    original = importLine + "\n" + original;
  }

  const patched = replaceFunctionBody(original);
  if (patched === null) {
    console.error("[ue-mcp] ERRO: Não conseguiu fazer patch em toJsonSchemaCompat");
    return false;
  }

  fs.writeFileSync(compatPath, patched, "utf-8");
  console.error("[ue-mcp] Schema patch aplicado no SDK ESM: $ref serão inlineados para compatibilidade Moonshot/Kimi");
  return true;
}

applyPatch();
